version: "3"
services:
    client:
        build:
          context: ./client
          dockerfile: Dockerfile
        image: myapp-client
        container_name: myapp-react-client
        ports:
            - "3000:3000"
        volumes:
            - ./client/src:/usr/app/src
            - ./client/public:/usr/app/public
        depends_on:
            - server
        networks:
          - app-network
        stdin_open: true
        tty: true
    server:
        build:
          context: ./server
          dockerfile: Dockerfile
        image: myapp-server
        container_name: myapp-node-server
        ports:
            - "8003:8003"
        volumes:
            - ./server/src:/usr/app/src
        networks:
          - app-network
        depends_on:
          - db
    db:
      image: mongo
      ports:
        - 27017:27017
      container_name: mongo-db
      networks:
        - app-network
      volumes:
        - mongo-data:/data/db

networks:
    app-network:
        driver: bridge

volumes:
    mongo-data:
      driver: local